on: push

jobs:
  build_image:
    uses: CubicrootXYZ/Workflows/.github/workflows/build_image.yaml@main
    with:
      docker_build_args: "--no-cache"
      docker_file_path: "./"
      image_name: "cubicrootxyz/golang-ci"
    secrets:
      dockerhub_user: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}